Making more generic commands

diff --git a/build_images.yml b/build_images.yml
--- a/build_images.yml
+++ b/build_images.yml
@@ -9,27 +9,20 @@ phases:
   install:
     commands:
       - if [ -z ${AWS_ACCOUNT_ID+x} ]; then AWS_ACCOUNT_ID=$(aws sts get-caller-identity | jq -r .Account); fi
+      - if [ -z ${VERSION+} ]; then echo "Missing required parameter VERSION" && exit 1; fi
       - REGISTRY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION:-$AWS_DEFAULT_REGION}.amazonaws.com/
       - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${REGISTRY_URI}
       - COMMIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION::7}
-      - EPOCH=`date +'%Y-%m-%d'`
-      - IMAGE_TAG=${COMMIT_HASH:=$EPOCH}
-      - if [ $USE_EPOCH -eq 1 ]; then IMAGE_TAG=$EPOCH; fi
+      - EPOCH=`date +'%Y%m%d'`
+      - SUFFIX=${COMMIT_HASH:=$EPOCH}
+      - if [ $USE_EPOCH -eq 1 ]; then SUFFIX=$EPOCH; fi
 
   build:
     commands:
-      - |
-          if [ -z ${ARCH+x} ]; then amazon-linux-extras enable python3.8
-            docker build -t python:${IMAGE_TAG} -f Dockerfile${VERSION:+.$VERSION} .
-            docker tag python:${IMAGE_TAG} ${REGISTRY_URI}python:${IMAGE_TAG}
-            docker tag python:${IMAGE_TAG} ${REGISTRY_URI}python:${IMAGE_TAG}-amd64
-            docker push ${REGISTRY_URI}python:${IMAGE_TAG}
-            docker push ${REGISTRY_URI}python:${IMAGE_TAG}-amd64
-          else
-            docker build --build-arg ARCH="-${ARCH}" -t python:${IMAGE_TAG}-${ARCH} -f Dockerfile${VERSION:+.$VERSION} .
-            docker tag python:${IMAGE_TAG}-${ARCH} ${REGISTRY_URI}python:${IMAGE_TAG}-${ARCH}
-            docker push ${REGISTRY_URI}python:${IMAGE_TAG}-${ARCH}
-          fi
+      - TAG=${VERSION}.${SUFFIX}
+      - docker build -t python:${TAG} ${ARCH:+--build-arg ARCH="-${ARCH}"} -f Dockerfile.${VERSION} .
+      - docker tag python:${TAG}${ARCH:+-$ARCH} ${REGISTRY_URI}python:${TAG}${ARCH:+-$ARCH}
+      - docker push ${REGISTRY_URI}python:${TAG}${ARCH:+-$ARCH}
 
     finally:
       - rm -rfv ~/.docker
